# Generated by Django 5.1.2 on 2024-11-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0003_privateaudio_file_type_privatedocument_file_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateaudio',
            name='file_type',
            field=models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], default='document', max_length=10),
        ),
        migrations.AlterField(
            model_name='privatedocument',
            name='file_type',
            field=models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], default='document', max_length=10),
        ),
        migrations.AlterField(
            model_name='privateimage',
            name='file_type',
            field=models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], default='document', max_length=10),
        ),
        migrations.AlterField(
            model_name='privatevideo',
            name='file_type',
            field=models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], default='document', max_length=10),
        ),
    ]
