# Generated by Django 5.1.2 on 2024-11-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0004_alter_privateaudio_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateaudio',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='privatedocument',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='privateimage',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='privatevideo',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
