# Generated by Django 5.1.2 on 2024-11-13 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0005_privateaudio_sender_name_privatedocument_sender_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateaudio',
            name='sender_name',
        ),
        migrations.RemoveField(
            model_name='privatedocument',
            name='sender_name',
        ),
        migrations.RemoveField(
            model_name='privateimage',
            name='sender_name',
        ),
        migrations.RemoveField(
            model_name='privatevideo',
            name='sender_name',
        ),
    ]
