# Generated by Django 5.1.3 on 2024-11-19 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0007_announcement_sharedfile_delete_sharedaudio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='privateaudio',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_sent_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privatedocument',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_sent_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privateimage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_sent_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privatevideo',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_sent_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
