# Generated by Django 5.1.3 on 2024-11-24 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0010_privatedocument_thumbnail_privateimage_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatedocument',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='privateimage',
            name='thumbnail',
        ),
    ]
