# Generated by Django 5.1.3 on 2024-11-20 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('feedback_date', models.DateTimeField(auto_now_add=True)),
                ('task_type', models.CharField(choices=[('non_exam', 'Non-exam'), ('cambridge', 'Cambridge'), ('aptis', 'Aptis'), ('ielts', 'Ielts'), ('trinity', 'Trinity'), ('eoi', 'Escuela Oficial de Idiomas')], max_length=20)),
                ('grade_awarded', models.FloatField()),
                ('grade_total', models.FloatField()),
                ('grade_percent', models.FloatField()),
                ('student_notes', models.TextField(blank=True)),
                ('teacher_notes', models.TextField(blank=True)),
                ('document_area', models.FileField(upload_to='student_work/')),
                ('send_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_as_teacher', to=settings.AUTH_USER_MODEL)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_as_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('start_offset', models.IntegerField()),
                ('end_offset', models.IntegerField()),
                ('comment', models.TextField()),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='Feedback_app.feedback')),
            ],
        ),
    ]
