# Generated by Django 5.1.3 on 2024-12-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('start_offset', models.IntegerField()),
                ('end_offset', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('feedback_date', models.DateTimeField(auto_now_add=True)),
                ('task_type', models.CharField(choices=[('Cambridge', 'Cambridge'), ('Aptis', 'Aptis'), ('EOI', 'Escuela Oficial de Idiomas'), ('IELTS', 'Ielts'), ('Trinity', 'Trinity'), ('(Homework task)', 'Homework Task'), ('(Essay)', 'Essay'), ('(Project)', 'Project'), ('*Other*', 'Other')], max_length=20)),
                ('grade_awarded', models.FloatField(blank=True, null=True)),
                ('grade_total', models.FloatField(blank=True, null=True)),
                ('grade_percent', models.FloatField(blank=True, null=True)),
                ('student_notes', models.TextField(blank=True)),
                ('teacher_notes', models.TextField(blank=True)),
                ('document_area', models.FileField(upload_to='student_work/')),
            ],
        ),
    ]
