# Generated by Django 5.1.3 on 2024-12-09 17:37

import Feedback_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('feedback_date', models.DateTimeField(auto_now_add=True)),
                ('task_type', models.CharField(choices=[('Cambridge', 'Cambridge'), ('Aptis', 'Aptis'), ('EOI', 'Escuela Oficial de Idiomas'), ('IELTS', 'Ielts'), ('Trinity', 'Trinity'), ('(Homework task)', 'Homework Task'), ('(Essay)', 'Essay'), ('(Project)', 'Project'), ('*Other*', 'Other')], max_length=20)),
                ('grade_awarded', models.FloatField(blank=True, null=True)),
                ('grade_total', models.FloatField(blank=True, null=True)),
                ('grade_percent', models.FloatField(blank=True, null=True)),
                ('student_notes', models.TextField(blank=True)),
                ('teacher_notes', models.TextField(blank=True)),
                ('document_area', models.FileField(upload_to='student_work/')),
                ('send_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_as_teacher', to=settings.AUTH_USER_MODEL)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_as_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('start_offset', models.IntegerField()),
                ('end_offset', models.IntegerField()),
                ('comment', models.TextField()),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='Feedback_app.feedback')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('instructions', models.TextField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='homework_attachments/', validators=[Feedback_app.models.validate_file_size])),
                ('submitted', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_homework', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_homework', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='homework_submissions/', validators=[Feedback_app.models.validate_file_size, Feedback_app.models.validate_file_extension])),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='Feedback_app.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
