# Generated by Django 5.1.3 on 2024-12-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='hidden_from_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='hidden_from_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
