# Generated by Django 5.1.3 on 2024-11-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='grade_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='task_type',
            field=models.CharField(choices=[('Cambridge', 'Cambridge'), ('Aptis', 'Aptis'), ('EOI', 'Escuela Oficial de Idiomas'), ('IELTS', 'Ielts'), ('Trinity', 'Trinity'), ('(Homework task)', 'Homework Task'), ('(Essay)', 'Essay'), ('(Project)', 'Project'), ('*Other*', 'Other')], max_length=20),
        ),
    ]
