# Generated by Django 5.1.3 on 2024-12-02 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Feedback_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='send_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_as_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_as_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotation',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='Feedback_app.feedback'),
        ),
    ]
