# Generated by Django 5.1.3 on 2024-11-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback_app', '0002_alter_feedback_grade_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='grade_percent',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
