# Generated by Django 5.1.3 on 2024-11-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback_app', '0003_alter_feedback_grade_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='grade_awarded',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='grade_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='grade_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
