# Generated by Django 5.1.3 on 2024-12-04 21:27

import Feedback_app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback_app', '0004_alter_homework_attachment_alter_homework_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=Feedback_app.models.homework_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'png', 'jpg', 'jpeg', 'wav', 'mp3', 'm4a', 'ogg', 'mp4', 'mov', 'avi', 'wmv', 'mkv']), Feedback_app.models.validate_file_size]),
        ),
    ]
