# Generated by Django 5.1.3 on 2024-12-04 22:48

import Feedback_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback_app', '0006_homework_submitted_alter_homework_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmission',
            name='file',
            field=models.FileField(upload_to='homework_submissions/', validators=[Feedback_app.models.validate_file_size, Feedback_app.models.validate_file_extension]),
        ),
    ]
