[build]
builder = "NIXPACKS"
buildCommand = "python manage.py collectstatic --noinput"

[deploy]
startCommand = "gunicorn Teaching_Website.wsgi:application"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[[proxy]]
domain = "linguashineproject-production.up.railway.app"
internalPort = 8000

[proxy.headers]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
Access-Control-Allow-Headers = "*"
