# Generated by Django 5.1.3 on 2024-11-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='receive_email_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
